AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on AWS Lambda (container image) + HTTP API

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures: [x86_64]   # or arm64 if you prefer
      Events:
        Root:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        Predict:
          Type: HttpApi
          Properties:
            Path: /predict
            Method: ANY
        Proxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

Outputs:
  ApiUrl:
    Description: "HTTP API URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"
