name: Deploy FastAPI to AWS

on:
  push:
    branches:
      - main   # deploy when code is pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v3

      # Set up Python (for SAM CLI if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install AWS SAM CLI
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      # Configure AWS credentials (store in GitHub Secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Build SAM
      - name: SAM Build
        run: sam build --use-container

      # Deploy to AWS
      - name: SAM Deploy
        run: |
          sam deploy \
            --stack-name fastapi-ml-stack \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-confirm-changeset
